apiVersion: apps/v1
kind: Deployment
metadata:
  name: cit262-groupx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cit262-groupx
  template:
    metadata:
      labels:
        app: cit262-groupx
    spec:
      containers:
      - name: cit262-groupx
        image: gcr.io/potent-galaxy-274115/cit262-groupx
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: ".5"
            memory: "500Mi"
          requests:
            cpu: ".25"
            memory: "250Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: cit262-groupx-service
spec:
  selector:
    app: cit262-groupx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: cit262-groupx-balancer
spec:
  backend:
    serviceName: cit262-groupx-service
    servicePort: 80  
